import {
  User,
  LandDocument,
  Parcel,
  ParcelLineageEvent,
  AuditLogEntry,
  SystemThresholds,
} from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'usr-officer-01',
    name: 'Sanjay Deshmukh',
    email: 'demo.officer@bhoomisutra.demo',
    role: 'OFFICER',
    designation: 'Taluka Revenue Officer / Tehsildar',
    department: 'Department of Revenue & Land Records',
    district: 'Pune',
    state: 'Maharashtra',
    isActive: true,
    isDemo: true,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'usr-admin-01',
    name: 'Dr. Arvind Rao',
    email: 'demo.admin@bhoomisutra.demo',
    role: 'ADMIN',
    designation: 'State Revenue Commissionerate Admin',
    department: 'Digital Land Governance Division',
    district: 'State HQ',
    state: 'Maharashtra',
    isActive: true,
    isDemo: true,
    createdAt: '2026-01-10T08:30:00Z',
  },
  {
    id: 'usr-citizen-01',
    name: 'Suresh Patil',
    email: 'demo.citizen@bhoomisutra.demo',
    role: 'CITIZEN',
    designation: 'Landholder & Agricultural Cultivator',
    department: 'Public Citizen Portal',
    district: 'Pune',
    state: 'Maharashtra',
    isActive: true,
    isDemo: true,
    createdAt: '2026-02-01T10:15:00Z',
  },
  {
    id: 'usr-officer-02',
    name: 'Priyanka Verma',
    email: 'priyanka.verma@rev.gov.demo',
    role: 'OFFICER',
    designation: 'Assistant Sub-Divisional Officer (SDO)',
    department: 'Sub-Divisional Revenue Office',
    district: 'Nashik',
    state: 'Maharashtra',
    isActive: true,
    isDemo: true,
    createdAt: '2026-02-12T11:00:00Z',
  },
];

export const SEED_PARCELS: Record<string, Parcel> = {
  'parcel-45-2': {
    id: 'parcel-45-2',
    ulpin: 'MH-PUN-HAV-045-002',
    surveyNumber: '45/2',
    subDivision: '2',
    village: 'Anandpur',
    tehsil: 'Haveli',
    district: 'Pune',
    state: 'Maharashtra',
    currentOwner: 'Suresh Patil',
    currentArea: 2.5,
    unit: 'Acre',
    classification: 'Agricultural (Jirayat Class I)',
  },
  'parcel-88-3b': {
    id: 'parcel-88-3b',
    ulpin: 'MH-NSK-KAL-088-03B',
    surveyNumber: '88/3B',
    subDivision: '3B',
    village: 'Kalyanpur',
    tehsil: 'Kalwan',
    district: 'Nashik',
    state: 'Maharashtra',
    currentOwner: 'Rajesh Sharma & Brother',
    currentArea: 1.35,
    unit: 'Acre',
    classification: 'Agricultural (Bagayat)',
  },
};

export const SEED_LINEAGE: Record<string, ParcelLineageEvent[]> = {
  'parcel-45-2': [
    {
      id: 'lin-45-01',
      parcelId: 'parcel-45-2',
      year: 1998,
      date: '1998-04-14',
      eventType: 'ORIGINAL_SURVEY',
      title: 'Original Cadastral Settlement Record',
      primaryParty: 'Ram Patil',
      areaBefore: 4.0,
      areaAfter: 4.0,
      unit: 'Acre',
      documentRef: 'Cadastral Survey Record #98/12',
      notes: 'Initial consolidation survey entry with intact boundaries.',
    },
    {
      id: 'lin-45-02',
      parcelId: 'parcel-45-2',
      year: 2008,
      date: '2008-08-19',
      eventType: 'SALE_TRANSFER',
      title: 'Registered Sale Deed Transfer',
      primaryParty: 'Ram Patil (Seller)',
      secondaryParty: 'Suresh Patil (Purchaser)',
      areaBefore: 4.0,
      areaAfter: 4.0,
      unit: 'Acre',
      documentRef: 'Sub-Registrar Deed #1084/2008',
      notes: 'Full parcel title transferred with mutation entry #1420.',
    },
    {
      id: 'lin-45-03',
      parcelId: 'parcel-45-2',
      year: 2018,
      date: '2018-05-10',
      eventType: 'SUBDIVISION',
      title: 'Cadastral Partition & Subdivision',
      primaryParty: 'Suresh Patil',
      areaBefore: 4.0,
      areaAfter: 2.5,
      unit: 'Acre',
      documentRef: 'Partition Order #SDO-2018-45',
      notes: 'Parent plot 4.00 Acre subdivided into Plot 45/1 (1.50 Acre) & Plot 45/2 (2.50 Acre). Sum = 4.00 Acre (Conserved).',
      subParcels: [
        { surveyNumber: '45/1', area: 1.5, owner: 'Mahesh Patil', ulpin: 'MH-PUN-HAV-045-001' },
        { surveyNumber: '45/2', area: 2.5, owner: 'Suresh Patil', ulpin: 'MH-PUN-HAV-045-002' },
      ],
    },
    {
      id: 'lin-45-04',
      parcelId: 'parcel-45-2',
      year: 2026,
      date: '2026-03-01',
      eventType: 'CURRENT_RECORD',
      title: 'Current Digitized 7/12 Extract',
      primaryParty: 'Suresh Patil',
      areaBefore: 2.5,
      areaAfter: 2.5,
      unit: 'Acre',
      documentRef: 'Digital RoR Extract #PUN-45-2-2026',
      notes: 'Active parcel ledger under AI-assisted verification.',
    },
  ],
  'parcel-88-3b': [
    {
      id: 'lin-88-01',
      parcelId: 'parcel-88-3b',
      year: 2002,
      date: '2002-03-11',
      eventType: 'ORIGINAL_SURVEY',
      title: 'Original Ancestral Holding Record',
      primaryParty: 'Gopal Sharma',
      areaBefore: 2.4,
      areaAfter: 2.4,
      unit: 'Acre',
      documentRef: 'Survey Record #NSK-02/88',
      notes: 'Parent ancestral holding recorded at 2.40 Acre.',
    },
    {
      id: 'lin-88-02',
      parcelId: 'parcel-88-3b',
      year: 2018,
      date: '2018-11-22',
      eventType: 'SUBDIVISION',
      title: 'Disputed Partition Deed',
      primaryParty: 'Gopal Sharma',
      secondaryParty: 'Rajesh & Brother',
      areaBefore: 2.4,
      areaAfter: 2.65,
      unit: 'Acre',
      documentRef: 'Partition Deed #8831/2018',
      notes: 'AREA MISMATCH DETECTED: Partition allotted Plot 88/3A (1.30 Acre) + Plot 88/3B (1.35 Acre) = 2.65 Acre. Exceeds parent 2.40 Acre by 0.25 Acre!',
      isViolation: true,
      subParcels: [
        { surveyNumber: '88/3A', area: 1.3, owner: 'Dinesh Sharma', ulpin: 'MH-NSK-KAL-088-03A' },
        { surveyNumber: '88/3B', area: 1.35, owner: 'Rajesh Sharma', ulpin: 'MH-NSK-KAL-088-03B' },
      ],
    },
  ],
};

export const INITIAL_THRESHOLDS: SystemThresholds = {
  clearScoreMin: 80,
  reviewScoreMin: 50,
  holdScoreMax: 49,
  enforceAreaConservationStrict: true,
  requireBiometricOfficerApproval: false,
};
